%% Import data from spreadsheet
% Script for importing data from the following spreadsheet:
%
%    Workbook:
%    /Users/mohammad/Documents/MyProject/Stage2014/data/France_1.xlsx
%    Worksheet: Sheet1
%
% To extend the code for use with different selected data or a different
% spreadsheet, generate a function instead of a script.

% Auto-generated by MATLAB on 2014/07/04 14:57:57

%% Import the data
[~, ~, raw] = xlsread('/Users/mohammad/Documents/MyProject/Stage2014/data/France_1.xlsx','Sheet1');
raw = raw(2:end,:);

%% Create output variable
data = reshape([raw{:}],size(raw));

%% Allocate imported array to column variable names
DatesCotations = data(:,1);
SpreadsCDS1 = data(:,2);
SpreadsCDS2 = data(:,3);
SpreadsCDS3 = data(:,4);
SpreadsCDS4 = data(:,5);
SpreadsCDS5 = data(:,6);
SpreadsCDS6 = data(:,7);
SpreadsCDS7 = data(:,8);
SpreadsCDS8 = data(:,9);
SpreadsCDS9 = data(:,10);
SpreadsCDS10 = data(:,11);

%% Clear temporary variables
clearvars data raw;